Repository UCF/Today-Utilities, pull requests merged in 2019-05, with the labels that each got.

#11 Added author byline to REST API results for posts; some file re-organization
  includes/today-feeds.php
  includes/today-main-site-feed-options.php
  includes/today-options-gmucf.php
  includes/today-options-main-site-feed.php
  today-utilities.php
Labels: enhancement

#12 Hf thumbnail fix
  includes/today-options-gmucf.php
Labels: bug

#13 Updated error that was throwing a notice
  includes/today-feeds.php
Labels: bug

#14 Added announcements feed back in
  includes/today-options-gmucf.php
Labels: bug, enhancement
